/* Generated by scripts/pieces.py from the baked cutouts. Do not edit. */
export interface Piece {
  readonly file: string;
  readonly width: number;
  readonly height: number;
}

export const PIECES = {
  proscenium: { file: "proscenium.webp", width: 1536, height: 1024 },
  footlights: { file: "footlights.webp", width: 1508, height: 672 },
  curtain: { file: "curtain.webp", width: 1407, height: 1024 },
  stallTeal: { file: "stallTeal.webp", width: 1261, height: 1011 },
  stallIndigo: { file: "stallIndigo.webp", width: 1287, height: 1020 },
  redBuilding: { file: "redBuilding.webp", width: 1477, height: 1013 },
  goldArch: { file: "goldArch.webp", width: 1361, height: 1007 },
  back: { file: "back.webp", width: 1536, height: 1024 },
  nightFar: { file: "nightFar.webp", width: 1536, height: 893 },
  nightMid: { file: "nightMid.webp", width: 1529, height: 999 },
  nightNear: { file: "nightNear.webp", width: 1536, height: 995 },
  slip: { file: "slip.webp", width: 1507, height: 1007 },
  lamp: { file: "lamp.webp", width: 1479, height: 983 },
  cloudA: { file: "cloudA.webp", width: 1460, height: 824 },
  cloudB: { file: "cloudB.webp", width: 1267, height: 995 },
  saathi: { file: "saathi.webp", width: 889, height: 1519 },
  shopper: { file: "shopper.webp", width: 981, height: 1523 },
  shopkeeper: { file: "shopkeeper.webp", width: 971, height: 1526 },
  tout: { file: "tout.webp", width: 964, height: 1534 },
} as const satisfies Record<string, Piece>;

export type PieceName = keyof typeof PIECES;

export function pieceSrc(name: PieceName): string {
  return `/stage/${PIECES[name].file}`;
}
