"""Bakes the generated cutouts into public/stage and writes src/stage/pieces.ts
with each piece's real trimmed size, so the layout never guesses a number.

Usage: python apps/landing/scripts/pieces.py <dir-with-pngs>
Requires Pillow. Every cutout is trimmed to its alpha bounding box with a
small margin and saved as WebP with alpha; the one opaque plate (the back of
the theatre) is saved without alpha.
"""
import os
import sys

from PIL import Image

PIECES = {
    "proscenium": "chrome-proscenium",
    "footlights": "chrome-footlights",
    "curtain": "curtain-half",
    "stallTeal": "flat-stall-teal",
    "stallIndigo": "flat-stall-indigo",
    "redBuilding": "flat-red-building",
    "goldArch": "flat-gold-arch",
    "back": "back-of-theatre",
    "nightFar": "night-far",
    "nightMid": "night-mid",
    "nightNear": "night-near",
    "slip": "prop-slip",
    "lamp": "prop-lamp",
    "cloudA": "prop-cloud-a",
    "cloudB": "prop-cloud-b",
    "saathi": "F-minimal-geometric",
    "shopper": "cast-shopper",
    "shopkeeper": "cast-shopkeeper",
    "tout": "cast-tout",
}
OPAQUE = {"back"}
PAD = 8


def bake(source: str, out: str, ts: str) -> None:
    os.makedirs(out, exist_ok=True)
    rows = []
    for name, stem in PIECES.items():
        im = Image.open(os.path.join(source, stem + ".png")).convert("RGBA")
        if name in OPAQUE:
            im = im.convert("RGB")
        else:
            box = im.getchannel("A").getbbox() or (0, 0, im.width, im.height)
            box = (
                max(0, box[0] - PAD),
                max(0, box[1] - PAD),
                min(im.width, box[2] + PAD),
                min(im.height, box[3] + PAD),
            )
            im = im.crop(box)
        im.save(os.path.join(out, name + ".webp"), quality=86, method=6)
        rows.append((name, im.width, im.height))
    os.makedirs(os.path.dirname(ts), exist_ok=True)
    write_ts(ts, rows)
    for name, w, h in rows:
        print(f"{name}: {w}x{h}")


def write_ts(path: str, rows) -> None:
    lines = [
        "/* Generated by scripts/pieces.py from the baked cutouts. Do not edit. */",
        "export interface Piece {",
        "  readonly file: string;",
        "  readonly width: number;",
        "  readonly height: number;",
        "}",
        "",
        "export const PIECES = {",
    ]
    for name, w, h in rows:
        lines.append(f'  {name}: {{ file: "{name}.webp", width: {w}, height: {h} }},')
    lines += [
        "} as const satisfies Record<string, Piece>;",
        "",
        "export type PieceName = keyof typeof PIECES;",
        "",
        "export function pieceSrc(name: PieceName): string {",
        "  return `/stage/${PIECES[name].file}`;",
        "}",
        "",
    ]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: pieces.py <dir-with-pngs>")
        sys.exit(1)
    here = os.path.dirname(os.path.abspath(__file__))
    app = os.path.dirname(here)
    bake(sys.argv[1], os.path.join(app, "public", "stage"), os.path.join(app, "src", "stage", "pieces.ts"))
