import type { AttackResult } from "../attacks/result.js";
import type { DetectorRow, FamilyRow, Matrix } from "./matrix.js";
import { byDetector, byFamily } from "./matrix.js";
import type { ScenarioResult } from "./types.js";

function pct(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

function confusion(matrix: Matrix): readonly string[] {
  return [
    "## Confusion matrix",
    "",
    "| | gateway allowed | gateway held | gateway blocked |",
    "|---|---|---|---|",
    `| **attack** (n=${matrix.attacks}) | ${matrix.falseAllows} false allow | 0 | **${matrix.trueBlocks} true block** |`,
    `| **benign** (n=${matrix.benign}) | **${matrix.trueAllows} true allow** | ${matrix.held} held | ${matrix.falseBlocks} false block |`,
    "",
    `- **False-positive rate:** ${matrix.falseBlocks}/${matrix.benign} = **${pct(matrix.falsePositiveRate)}**`,
    ...matrix.surfaces.map(
      (row) =>
        `  - ${row.surface} surface: ${row.falseBlocks}/${row.total} = **${pct(row.rate)}**`,
    ),
    `- **Attack recall:** ${matrix.trueBlocks}/${matrix.attacks} = **${pct(matrix.recall)}**`,
    `- A held cart is counted as an allow: the purchase completes after the window or on one tap.`,
    "",
  ];
}

function attackTable(attacks: readonly AttackResult[]): readonly string[] {
  return [
    "## True blocks - the three live attacks",
    "",
    "| attack | blocked | reason codes | ledger seq |",
    "|---|---|---|---|",
    ...attacks.map(
      (attack) =>
        `| ${attack.attackId} ${attack.title} | ${attack.blocked ? "yes" : "**NO**"} | ${attack.steps
          .map((step) => step.reasonCode ?? "-")
          .join(", ")} | ${attack.ledgerSeq ?? "-"} |`,
    ),
    "",
  ];
}

function falseBlockTable(scenarios: readonly ScenarioResult[]): readonly string[] {
  const blocked = scenarios.filter((scenario) => scenario.outcome === "blocked");
  if (blocked.length === 0) {
    return ["## False blocks", "", "None. Every benign scenario was allowed.", ""];
  }
  return [
    "## False blocks and what each one costs",
    "",
    "| id | scenario | detector | reason_code | remedy | cost |",
    "|---|---|---|---|---|---|",
    ...blocked.map(
      (s) =>
        `| ${s.id} | ${s.description} | \`${s.detector ?? "-"}\` | \`${s.reasonCode ?? "-"}\` | ${s.remedy ?? "-"} | ${s.cost ?? "-"} |`,
    ),
    "",
  ];
}

function detectorTable(rows: readonly DetectorRow[]): readonly string[] {
  if (rows.length === 0) {
    return [];
  }
  return [
    "## Per-detector attribution (false blocks only)",
    "",
    "| detector | false blocks | reason codes | scenarios |",
    "|---|---|---|---|",
    ...rows.map(
      (row) =>
        `| \`${row.detector}\` | ${row.blocks} | ${row.reasonCodes.map((c) => `\`${c}\``).join(", ")} | ${row.scenarios.join(", ")} |`,
    ),
    "",
  ];
}

function familyTable(rows: readonly FamilyRow[]): readonly string[] {
  return [
    "## By corpus family",
    "",
    "| family | scenarios | false blocks | rate |",
    "|---|---|---|---|",
    ...rows.map(
      (row) =>
        `| ${row.family} | ${row.total} | ${row.blocked} | ${pct(row.blocked / row.total)} |`,
    ),
    "",
  ];
}

function fullTable(scenarios: readonly ScenarioResult[]): readonly string[] {
  return [
    "## Every scenario",
    "",
    "| id | surface | scenario | outcome | reason_code |",
    "|---|---|---|---|---|",
    ...scenarios.map(
      (s) =>
        `| ${s.id} | ${s.surface} | ${s.description} | ${s.outcome} | ${s.reasonCode === null ? "-" : `\`${s.reasonCode}\``} |`,
    ),
    "",
  ];
}

export interface ReportInput {
  readonly matrix: Matrix;
  readonly attacks: readonly AttackResult[];
  readonly scenarios: readonly ScenarioResult[];
  readonly generatedAt: string;
  readonly notes: readonly string[];
}

const HOW_TO_READ: readonly string[] = [
  "## How to read this",
  "",
  "The benign corpus is **deliberately adversarial to the detectors**: catalog copy",
  "chosen because it innocently contains trigger words, amounts sitting exactly on",
  "envelope and cap boundaries, covenant edits that tighten rather than loosen. The",
  "headline rate is therefore *not* \"one ordinary write in three is refused\" - it is",
  "\"one write in three, among writes picked to look like attacks while being",
  "harmless, is refused\". The per-family and per-surface splits below are the honest",
  "way to read it, and the purchase surface is the one that can cost a sale.",
  "",
];

/** The honest number, whatever it is: a wrong one is worse than a high one. */
export function markdownReport(input: ReportInput): string {
  return [
    "# Covenant - adversarial results and false-positive measurement",
    "",
    `Generated by \`pnpm --filter @covenant/attacks fp\` at ${input.generatedAt}.`,
    "Every row below is a live HTTP call against a running gateway. Nothing is simulated.",
    "",
    ...HOW_TO_READ,
    ...confusion(input.matrix),
    ...(input.notes.length === 0
      ? []
      : ["## Findings", "", ...input.notes.flatMap((note) => [note, ""])]),
    ...attackTable(input.attacks),
    ...falseBlockTable(input.scenarios),
    ...detectorTable(byDetector(input.scenarios)),
    ...familyTable(byFamily(input.scenarios)),
    ...fullTable(input.scenarios),
  ].join("\n");
}
